#!/bin/bash

: ${BBL_WORKING_DIR:?"Need to set BBL_WORKING_DIR non-empty. Where is your bbl-state.json??"}

current_project_id=$(gcloud config list --format 'value(core.project)')
echo "Current Project ID: " $current_project_id
project_id=concourse-gcp-bbl
if [ "$current_project_id" != "$project_id" ]
then
  echo "Project ID should be" $project_id
  exit 1
fi

service_account_name=concourse-gcp-bbl

# gcloud iam service-accounts delete ${service_account_name}
gcloud iam service-accounts create ${service_account_name}

iam_account=${service_account_name}@${project_id}.iam.gserviceaccount.com
echo "Setting up IAM account: " $iam_account
gcloud iam service-accounts keys create --iam-account=$iam_account $BBL_WORKING_DIR/${service_account_name}.key.json
member=serviceAccount:${iam_account}
gcloud projects add-iam-policy-binding ${project_id} --member=$member --role='roles/editor'

region=europe-west2
zone=europe-west2-a
echo "Please run 'bbl up --gcp-zone $zone --gcp-region $region --gcp-service-account-key ${BBL_WORKING_DIR}/${service_account_name}.key.json --gcp-project-id $project_id --iaas gcp'"
